from tkinter import *
from database import *
def add():
    line = id.get() + '-' + name.get() + '-' + year.get()
    save(line)
    show()
def show():
    sv = read()
    listbox.delete(0, END)
    for i in sv:
        listbox.insert(END, i)
root= Tk()
id = StringVar()
name = StringVar()
year = StringVar()
root.title('QLSV')
root.minsize(500, 500)
Label(root, text='Ung dung quan li sinh vien', fg='blue', font=('cambria', 16), width=20).grid(row=0)
listbox=Listbox(root, width=80, height=20)
listbox.grid(row=1, columnspan=2)
show()
Label(root, text='MSV:', fg='blue', font=('cambria', 8), width=10).grid(row=2, column=0)
Entry(root,width=30, textvariable=id).grid(row=2, column=1)
Label(root, text='Name:', fg='blue', font=('cambria', 8), width=10).grid(row=3, column=0)
Entry(root,width=30, textvariable=name).grid(row=3, column=1)
Label(root, text='Date:', fg='blue', font=('cambria', 8), width=10).grid(row=4, column=0)
Entry(root,width=30, textvariable=year).grid(row=4, column=1)
button = Frame(root)
Button(button, text='Add', command=add).pack(side=LEFT)
Button(button, text='View', command=show).pack(side=LEFT)
Button(button, text='Sort').pack(side=LEFT)
Button(button, text='Close', command=root.quit).pack(side=LEFT)
button.grid(row=5, column=1)
root.mainloop()